import{a as l,i as m}from"./assets/vendor-98a16590.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();l.defaults.headers.common["x-api-key"]="live_lRZEIkhbwtvfK1yPxtwtCkUy1ANlxpe35OrJl3neeWXcmXVdB9lEFrv8VKk1XIgE";const p="https://api.thecatapi.com",h="v1/breeds",g="v1/images/search";function d(t){return l.get(t).then(e=>e.status>=400?new Error(e.statusText):e.data)}function u(t,e=""){return`${p}/${t}${e}`}function y(){const t=u(h);return d(t)}function v(t){const e=new URLSearchParams({breed_ids:t}),a=u(g,`?${e}`);return d(a)}const n={selectBreed:document.querySelector(".breed-select"),pLoader:document.querySelector(".loader"),divCatInfo:document.querySelector(".cat-info")};function L(t){const e=t.map(a=>`<option value="${a.id}">${a.name}</option>`).join("");n.selectBreed.insertAdjacentHTML("afterbegin",e),s(n.pLoader,!1),s(n.selectBreed,!0)}function b({url:t,breeds:e}=cat){const a=`
        <img class="image" src="${t}" alt="${e[0].name}" />
        <div class="text-info-block">
            <h2 class="breed-name">${e[0].name}</h2>
            <p class="description">${e[0].description}</p>
            <p><span class="temperament">Temperament:</span> ${e[0].temperament}</p>
        </div>
    `;n.divCatInfo.innerHTML=a,s(n.pLoader,!1),s(n.selectBreed,!0),s(n.divCatInfo,!0)}function f(){s(n.pLoader,!1),m.show({message:"Oops! Something went wrong! Try reloading the page!",messageColor:"white",backgroundColor:"tomato",timeout:4e3,position:"topCenter"})}function s(t,e){e?t.removeAttribute("hidden"):t.setAttribute("hidden","")}s(n.divCatInfo,!1);y().then(t=>L(t)).catch(t=>f());const C=t=>{n.divCatInfo.innerHTML="",s(n.pLoader,!0),s(n.selectBreed,!1),s(n.divCatInfo,!1),v(t.target.value).then(e=>b(e[0])).catch(e=>f())};n.selectBreed.addEventListener("change",C);
//# sourceMappingURL=commonHelpers.js.map
