import{a as l,S as p,i as m}from"./assets/vendor-c6813687.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(r){if(r.ep)return;r.ep=!0;const n=a(r);fetch(r.href,n)}})();l.defaults.headers.common["x-api-key"]="live_lRZEIkhbwtvfK1yPxtwtCkUy1ANlxpe35OrJl3neeWXcmXVdB9lEFrv8VKk1XIgE";const h="https://api.thecatapi.com",g="v1/breeds",y="v1/images/search";function d(t){return l.get(t).then(e=>e.status>=400?new Error(e.statusText):e.data)}function u(t,e=""){return`${h}/${t}${e}`}function S(){const t=u(g);return d(t)}function v(t){const e=new URLSearchParams({breed_ids:t}),a=u(y,`?${e}`);return d(a)}const b={showSearch:!1,placeholderText:"Select cat's breed"},C={afterChange:E},s={selectWraper:document.querySelector(".select-wraper"),selectBreed:new p({select:".breed-select",settings:b,events:C}),pLoader:document.querySelector(".loader"),divCatInfo:document.querySelector(".cat-info")};function L(t){const e=[{placeholder:!0,text:"Select cat's breed"}];t.forEach(a=>e.push({text:`${a.name}`,value:`${a.id}`})),s.selectBreed.setData(e),o(s.pLoader,!1),o(s.selectWraper,!0)}function w({url:t,breeds:e}=cat){const a=`
        <img class="image" src="${t}" alt="${e[0].name}" />
        <div class="text-info-block">
            <h2 class="breed-name">${e[0].name}</h2>
            <p class="description">${e[0].description}</p>
            <p><span class="temperament">Temperament:</span> ${e[0].temperament}</p>
        </div>
    `;s.divCatInfo.innerHTML=a,o(s.pLoader,!1),o(s.selectWraper,!0),o(s.divCatInfo,!0)}function f(){o(s.pLoader,!1),m.show({message:"Oops! Something went wrong! Try reloading the page!",messageColor:"white",backgroundColor:"tomato",timeout:4e3,position:"topCenter"})}function o(t,e){e?t.removeAttribute("hidden"):t.setAttribute("hidden","")}o(s.selectWraper,!1);o(s.divCatInfo,!1);S().then(t=>L(t)).catch(t=>f());function E(t){t[0].placeholder||(o(s.pLoader,!0),o(s.divCatInfo,!1),s.divCatInfo.innerHTML="",v(t[0].value).then(e=>w(e[0])).catch(e=>f()))}
//# sourceMappingURL=commonHelpers.js.map
